### PR TITLE
memory-game

### PR DESCRIPTION
**Pull request by 2devyank**
@Welf06 please check my pr I have added my project memory-game
Issue no #10

### CODE REVIEW

**Comment by Welf06** [comment]
@2devyank please pull the latest changes to the landing page which has fixed the redirecting to the subpage and add a card for your project 
I will merge your pr after this : )

**Comment by 2devyank** [comment]
@Welf06 I have done the necessary changes ples check

**Comment by Welf06** [comment]
@2devyank there are some conflicts in tools.html, can you look into it

**Comment by Welf06** [comment]
Make sure that your repo is at its latest version, before you make the change

**Comment by Welf06** [comment]
@2devyank I saw your memory game, can you improve upon the UI of the page? You can take reference from sites like codepen

**Pull request closed without merging**
