### PR TITLE
Added updated README.md

### LINKED ISSUE #1: Rewrite Readme.md
Currently the Readme is really bland, It requires being rewritten in a creative way (including images and other graphics wherever possible). Things it should include:
->Introduction
->Maintainers
->Goal
->Showcase
->How to run it locally
->Contributors (Easy to add more entries in future)
An example to get you started https://github.com/vishal-lokare/AutoJoomer/blob/main/README.md

### PR DESCRIPTION
**Pull request by hackeramitkumar**
I have added a markdown file. Which have complete details of our project.

### CODE REVIEW

**Comment by hackeramitkumar** [comment]
@Welf06 Please PR this issue and let me know if any changes are required.

**Comment by hackeramitkumar** [comment]
@Welf06 Please  lable to this PR by hactoberfest-accepted.

**Comment by Welf06** [comment]
Yeah I will definitely add the label before merging it. Just 2 changes to do
1. You have mentioned Autojoomer at the end in license
2. Put the first para in wordtune for better grammer
I will merge it then

**Comment by hackeramitkumar** [comment]
Yeah sure I will make the changes.

**Comment by hackeramitkumar** [comment]
Can you tell what content should I add for the first paragraph?

**Comment by Welf06** [comment]
Basic-Web-Pages is an Open Source project that is a part of Hacktoberfest 2022. In it, you can find simple HTML, CSS, and JavaScript web development projects. Our goal is to create a repository of beautifully designed simple websites that can serve as a reference for those just getting started with Web Development. Compared to other complex projects, our repository is also a great place for people to start their Open Source journey. Anyone interested in contributing to our project is welcome.

**Comment by Welf06** [comment]
This is what I came up with

**Comment by Welf06** [comment]
and maybe try putting the contributing section in points rather than a para
apart from this the README looks amazing, great work

**Comment by Welf06** [comment]
@hackeramitkumar any issues?

**Comment by Welf06** [comment]
Since there is not much work left I am merging it
@hackeramitkumar Thank you for your contribution ✨

**Comment by hackeramitkumar** [comment]
.....................................

Amit would like to stay in touch on LinkedIn.

Amit kumar
SWE Intern @Cisco || LFX'23 @Kyverno || GSoC’22 || GSoC'23 Mentor || CAPI v1.4, v1.5, v1.6 Release Team || Coding Club admin @MNNIT Allahabad 
India

View profile https://www.linkedin.com/comm/in/amit3210?trk=eml-guest-invite-pprofile-link-cta&trkEmail=eml-email_m2g_invite_single_01-null-373-null-null-4opfyy%7Elryz4igo%7E52-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3B01o34NDMRReXXwyEoURATg%3D%3D

Confirm that you know Amit https://www.linkedin.com/e/v2?e=4opfyy-lryz4igo-52&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3B01o34NDMRReXXwyEoURATg%3D%3D&t=suwj&tracking=eml-guest-invite-cta&ek=email_m2g_invite_single_01&validationToken=0A3AOckB&invitationId=7157725241278918656


.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=4opfyy-lryz4igo-52&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_m2g_invite_single_01&li=381&m=unsub&ts=unsub&loid=AQGyZ1INuJh1NQAAAY1VcUntB3jWMNPTPoMveOy5Rz5RRgrOfbagmqz2y-zsoj-FNItSsAh8SApm0u6CrxWxkqhX3rUKh2_haOJmopceTcyUEQtWXXTbRcsfV2k4jiVvgV3jvvXbadJDpL-CdlcJxhec1LII2lpHrw&eid=4opfyy-lryz4igo-52

Help: https://www.linkedin.com/e/v2?e=4opfyy-lryz4igo-52&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3B01o34NDMRReXXwyEoURATg%3D%3D&a=customerServiceUrl&ek=email_m2g_invite_single_01&li=380&m=footer&ts=help&articleId=67


You are receiving Invitation emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to ***@***.***

© 2024 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request merged**
