### PR TITLE
hacktoberfest-2022

### PR DESCRIPTION
**Pull request by Naisargika1402**
Please kindly preview my project and accordingly add it to your repo with label hacktoberfest.

### CODE REVIEW

**Comment by Welf06** [comment]
@Naisargika1402 your calendar app looks good, I will merge it after you:
> Pull the latest change (i.e )
> Add it to tools.html (i.e clicking on the card would take you to the calender app)
> Name it Calender App - 2

**Comment by Naisargika1402** [comment]
> @Naisargika1402 your calendar app looks good, I will merge it after you:
> 
> > Pull the latest change (i.e )
> > Add it to tools.html (i.e clicking on the card would take you to the calender app)
> > Name it Calender App - 2

I didn't quite understand what exactly I have to do even though you so elaborately explained. Can you please kindly explain again exactly what I have to do as I'm completely new to GitHub.

**Comment by Welf06** [comment]
Ok, so you forked my repo right? so when you open the forked repo, it will show on top if your fork is up to date with the parent repo(my repo), if it is you can skip the first part 
>Pull the latest change (i.e )

**Comment by Welf06** [comment]
image
>Second you see various cards right? add a card for your page so that when you click on the card you get redirected to your page i.e calender app-2/index.html and add a screenshot of your website in the card for the image

**Comment by Welf06** [comment]
>Name your folder calender app-2

**Comment by Welf06** [comment]
@Naisargika1402 I hope this clears it up
If you have any more queries, don't hesitate to ask here : )

**Comment by Naisargika1402** [comment]
> Ok, so you forked my repo right? so when you open the forked repo, it will show on top if your fork is up to date with the parent repo(my repo), if it is you can skip the first part
> 
> > Pull the latest change (i.e )

When I'm clicking the sync fork button its showing "This branch is not behind the upstream Welf06:main"

**Comment by Naisargika1402** [comment]
> image
> 
> > Second you see various cards right? add a card for your page so that when you click on the card you get redirected to your page i.e calender app-2/index.html and add a screenshot of your website in the card for the image

So I have to actually write the code for the card in tool.html to redirect it to my project?

**Comment by Welf06** [comment]
@Naisargika1402 just add a card for your subpage,

> > image
> > > Second you see various cards right? add a card for your page so that when you click on the card you get redirected to your page i.e calender app-2/index.html and add a screenshot of your website in the card for the image
> 
> So I have to actually write the code for the card in tool.html to redirect it to my project?

Just make a card for your subpage, @GyanPrakashRaj is working on redirecting it to the subpages

**Comment by Welf06** [comment]
But if you can @Naisargika1402 that would be great,.aine the point of hacktoberfest is to learn

**Comment by Naisargika1402** [comment]
> @Naisargika1402 just add a card for your subpage,
> 
> > > image
> > > > Second you see various cards right? add a card for your page so that when you click on the card you get redirected to your page i.e calender app-2/index.html and add a screenshot of your website in the card for the image
> > 
> > 
> > So I have to actually write the code for the card in tool.html to redirect it to my project?
> 
> Just make a card for your subpage, @GyanPrakashRaj is working on redirecting it to the subpages

Screenshot (2656)

Is this OK?

**Comment by GyanPrakashRaj** [comment]
Hlw... @Naisargika1402 ,

Your posted picture of changes doesn't look  or match the criteria mentioned here, Kindly recheck https://github.com/Welf06/Basic-Webpages/pull/12#issuecomment-1265545295
and it looks like you have removed the previous action of the background while adding your calendar app, Re-design your tools.html page and match the given changes, and please Don't lose the previous changes made by other developers.

I request @Welf06  to merge the  https://github.com/Welf06/Basic-Webpages/pull/14 first and then 
consider https://github.com/Welf06/Basic-Webpages/pull/12#issuecomment-1266321434 to get merged.

**Comment by Naisargika1402** [comment]
> Hlw... @Naisargika1402 ,
> 
> Your posted picture of changes doesn't look or match the criteria mentioned here, Kindly recheck [#12 (comment)](https://github.com/Welf06/Basic-Webpages/pull/12#issuecomment-1265545295) and it looks like you have removed the previous action of the background while adding your calendar app, Re-design your tools.html page and match the given changes, and please Don't lose the previous changes made by other developers.
> 
> I request @Welf06 to merge the #14 first and then consider [#12 (comment)](https://github.com/Welf06/Basic-Webpages/pull/12#issuecomment-1266321434) to get merged.

Hi @GyanPrakashRaj 
Don't worry I have not made any commits of the changes shown in the pic.I'm just asking whether this was to done or something else?

**Comment by Welf06** [comment]
@Naisargika1402, @GyanPrakashRaj has fixed the landing page now, you can now proceed to pull the new changes and add your calendar app as a new card called "calender-2".
After this I will merge your pr : )

**Comment by Naisargika1402** [comment]
> @Naisargika1402, @GyanPrakashRaj has fixed the landing page now, you can now proceed to pull the new changes and add your calendar app as a new card called "calender-2". After this I will merge your pr : )

Hello @Welf06 
Done! Can you kindly verify if its right?

**Comment by GyanPrakashRaj** [comment]
> > @Naisargika1402, @GyanPrakashRaj has fixed the landing page now, you can now proceed to pull the new changes and add your calendar app as a new card called "calender-2". After this I will merge your pr : )
> 
> Hello @Welf06 Done! Can you kindly verify if its right?
@Naisargika1402 
Great work with great dedication, Wish you all the best in your coding journey :metal: :clap:

**Comment by GyanPrakashRaj** [comment]
hey @Naisargika1402,
I just visited your changes, I here to say that there was a button on the footer (Back to Home ) which is unavailable after your change.

I request @Welf06  to assign a task to @Naisargika1402 to create a button on footer for back to home and the GitHub link of this repo on the <tools.html> page.

**Comment by Welf06** [comment]
@Naisargika1402 Good Job ✨ 
I will merge this pr, either you or @GyanPrakashRaj can raise an issue to add the back to home button

**Comment by Welf06** [comment]
@Naisargika1402 Good Job ✨ 
I will merge this pr, either you or @GyanPrakashRaj can raise an issue to add the back to home button

**Comment by Naisargika1402** [comment]
> hey @Naisargika1402, I just visited your changes, I here to say that there was a button on the footer (Back to Home ) which is unavailable after your change.
> 
> I request @Welf06 to assign a task to @Naisargika1402 to create a button on footer for back to home and the GitHub link of this repo on the <tools.html> page.

@GyanPrakashRaj 
Yeah I saw it rn, actually its still there I mean when I'm reducing the width of the screen its visible but when in full desktop screen its not visible. I guess its got do something with style part of the footer and I'm not able to realize what it is exactly even after analyzing it for some time .

**Comment by Naisargika1402** [comment]
> @Naisargika1402 Good Job ✨ I will merge this pr, either you or @GyanPrakashRaj can raise an issue to add the back to home button

@Welf06 
Done!

**Pull request merged**
